import { useStore } from "@store/index";
import "bootstrap/dist/css/bootstrap.min.css";
import Head from "next/head";
import React from "react";
import { Provider } from "react-redux";
import { persistStore } from "redux-persist";
import { PersistGate } from "redux-persist/integration/react";
import "../src/sass/App.scss";
import "../src/sass/Custom.scss";
function MyApp({ Component, pageProps }) {
  const store = useStore(pageProps.initialReduxState);
  const persistor = persistStore(store);
  return (
    <React.StrictMode>
      <Provider store={store}>
        <PersistGate loading={null} persistor={persistor}>
          <Head>
            <title>Shopify Frontend</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Component {...pageProps} />
        </PersistGate>
      </Provider>
    </React.StrictMode>
  );
}

export default MyApp;
