import Head from "next/head";
import React from "react";
import "../src/styles/custom.scss";
import "../src/styles/main.scss";
import "../src/styles/theme.scss";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Shopify Frontend</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
